### ISSUE TITLE
[2.0.5] Options handling functions raise "Attribute Error" on Windows

### ISSUE THREAD

**Issue by smandyscom** [RaiMan/SikuliX1#434]
Hi There , I am working on sikulixide-2.0.5 on windows. Now I would like to utilize user properties write/read functions to implement persistence of application parameters, So that I am learning as the part of reference shown : https://sikulix-2014.readthedocs.io/en/latest/globals.html#saveOpts

The question is , whatever I call any persistence-related API with fix term of _Opt_ , for example _makeOpts()_ , the engine would keep answer me following error, How do I get it works? Thanks in advance for your help

_[error] AttributeError ( 'org.sikuli.script.support.RunTime' object has no attribute 'makeOpts'_

**Comment by RaiMan** [comment]
I am really sorry for that. Somehow this feature is completely lost in space :-((

I will revise/restore it with the 2.0.6.

Meanwhile I can give you a workaround:

- create an empty file name-it wherever you want

Now in the IDE:
```
import org.sikuli.script.Options as Opt
opts = Opt("<absolute-Path-to>/name-it")
print opts.getOption("someOpt", "empty")
opts.setOption("someOpt", "testOK")
opts.saveOptions()
```

- at first run you will get empty 
- at second and more runs you will get testOK

If you want to work with that solution, feel free to come back for more information

**Comment by julienmerconsulting** [comment]
[![Status](https://img.shields.io/badge/Status-archive%20cleanup-d73a49?style=flat-square&logo=github)](.) [![Repo](https://img.shields.io/badge/please%20refile-oculix--org%2FOculix-0969da?style=flat-square&logo=github)](https://github.com/oculix-org/Oculix/issues/new/choose)

Hi @smandyscom — `oculix-org/SikuliX1` is now an archived legacy mirror; active maintenance has moved to **[oculix-org/Oculix](https://github.com/oculix-org/Oculix)** since April 2026.

Your report still has merit but it needs to be evaluated against the current OculiX architecture, which is significantly different (new modules: MCP Server, Reporter, Modern Recorder, Apertix OpenCV 4.10.0, Legerix Tesseract bundle, Java 17 native, Apple Silicon native, etc.).

If this is still relevant to you, please open a fresh issue at https://github.com/oculix-org/Oculix/issues/new/choose — for bugs, please re-test against `v3.0.3-rc3` first and include repro steps; for enhancements, a quick rationale on how it fits the OculiX 3.x scope. Active triage there.

Closing this one for legacy archive cleanup.

— @julienmerconsulting (OculiX maintainer)

---
_Generated by [Claude Code](https://claude.ai/code)_
