### ISSUE TITLE
mvn clean install failed with "package java.awt.desktop does not exist"

### ISSUE THREAD

**Issue by cpk011** [RaiMan/SikuliX1#79]
@RaiMan,

I cloned and tried to build Sikulix but got the following error messages:

[ERROR] /Users/peter/SikuliX1/IDE/src/main/java/org/sikuli/idesupport/IDEMacSupport.java:[10,1] package java.awt.desktop does not exist
[ERROR] /Users/peter/SikuliX1/IDE/src/main/java/org/sikuli/idesupport/IDEMacSupport.java:[17,39] cannot find symbol
  symbol: class AboutHandler
...

Here is the mvn -X clean install output.
[mvn-out.txt](https://github.com/RaiMan/SikuliX1/files/2889548/mvn-out.txt)

**Comment by RaiMan** [comment]
see:
https://answers.launchpad.net/sikuli/+question/678659

**Comment by cpk011** [comment]
@RaiMan, the above link talks about IntelliJ Linux build issue and you recommended that the person deletes IDEMacSupport.java. 

I am not using IntelliJ and I am trying to build using MacBook Pro with MacOS Mojave 10.14.2. I do not think I should delete IDEMacSupport.java.

**Comment by RaiMan** [comment]
Sorry, but I made my life too easy ;-)

Nevertheless: the cause of your problem is mentioned in my linked answer: Java 8 ;-)
With Java 8 you have to remove the class even on macOS (I am developing on Java 11 with a target bytecode of Java 8)

**Comment by cpk011** [comment]
I removed IDEMacSupport.java and the build worked. Thank you.
